# Generated by Django 3.0.6 on 2020-05-11 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sales_person',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='business', to='user.SalesPerson'),
        ),
    ]
